// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx-x_1UApxrEbZ1JhhYhdXE1MenjlBNhg',
    appId: '1:141014588559:web:797982881468f2da44e4fa',
    messagingSenderId: '141014588559',
    projectId: 'matches-c26c7',
    authDomain: 'matches-c26c7.firebaseapp.com',
    storageBucket: 'matches-c26c7.appspot.com',
    measurementId: 'G-54YTKVFT7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuwGWnQNReRpFEXIHoyyXJSS40pQFwqvw',
    appId: '1:141014588559:android:907181dcd56a873d44e4fa',
    messagingSenderId: '141014588559',
    projectId: 'matches-c26c7',
    storageBucket: 'matches-c26c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCERk6cpC5-gco5m4PRhMLUEYuVfDa3wQo',
    appId: '1:141014588559:ios:018342cba02e931344e4fa',
    messagingSenderId: '141014588559',
    projectId: 'matches-c26c7',
    storageBucket: 'matches-c26c7.appspot.com',
    iosClientId: '141014588559-r7qcgghqqihu9uj2hf7qn2goct57an7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasmmp23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCERk6cpC5-gco5m4PRhMLUEYuVfDa3wQo',
    appId: '1:141014588559:ios:193c51eaf8749f2944e4fa',
    messagingSenderId: '141014588559',
    projectId: 'matches-c26c7',
    storageBucket: 'matches-c26c7.appspot.com',
    iosClientId: '141014588559-j50cclv29jshnvkmdbftr3j1125111te.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasmmp23.RunnerTests',
  );
}
